pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                bat 'python -m pip install -U pip'
                bat 'python -m pip install -e .[dev]'
            }
        }

        stage('Test') {
            steps {
                bat 'python -m pytest sample_sut/tests tests -q'
            }
        }
    }
}